### ISSUE TITLE
Typing Symphony Not Working - Closing After About 5 Seconds

### ISSUE THREAD

**Issue by ALarsonX** [hereafter/typing-symphony#1]
I am experiencing a problem with Typing Symphony on my HP Envy laptop (Windows 10).  It worked very well when I first installed the program earlier this year.  I noticed today that the sound was not being made when I typed, so I have tried the following:
     Opening the program again
     Reinstalling the program
Each time I open the program, it stays open about 5 seconds, then closes itself.  Please let me know what can be done to fix this problem with the program.  I really enjoy the program, and I would very much like for it to work again.  Thank you.

Anita Larson
anitalarson@wildblue.net

**Comment by hereafter** [comment]
could you please try to reinstall the following packages from Microsoft?

https://aka.ms/vs/16/release/vc_redist.x64.exe
https://aka.ms/vs/16/release/vc_redist.x86.exe

Install both if you could then re-install the application again from the store
to see if it works now?

**Comment by ALarsonX** [comment]
Worked.  Thank you very much.  😊

 

Anita Larson

anitalarson@wildblue.net <mailto:anitalarson@wildblue.net>
